// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package goqueries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
  id, tenant_id, type, owner_type, label, platform_identifier,
  credentials_encrypted, capabilities, status, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, tenant_id, type, owner_type, label, platform_identifier, credentials_encrypted, capabilities, status, created_at
`

type CreateAccountParams struct {
	ID                   uuid.UUID `db:"id" json:"id"`
	TenantID             uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Type                 string    `db:"type" json:"type"`
	OwnerType            string    `db:"owner_type" json:"owner_type"`
	Label                string    `db:"label" json:"label"`
	PlatformIdentifier   string    `db:"platform_identifier" json:"platform_identifier"`
	CredentialsEncrypted []byte    `db:"credentials_encrypted" json:"credentials_encrypted"`
	Capabilities         []string  `db:"capabilities" json:"capabilities"`
	Status               string    `db:"status" json:"status"`
	CreatedAt            time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.TenantID,
		arg.Type,
		arg.OwnerType,
		arg.Label,
		arg.PlatformIdentifier,
		arg.CredentialsEncrypted,
		arg.Capabilities,
		arg.Status,
		arg.CreatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.OwnerType,
		&i.Label,
		&i.PlatformIdentifier,
		&i.CredentialsEncrypted,
		&i.Capabilities,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts
WHERE id = $1 AND tenant_id = $2
`

type DeleteAccountParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, tenant_id, type, owner_type, label, platform_identifier, credentials_encrypted, capabilities, status, created_at FROM accounts WHERE id = $1
`

// Resolve an account by id without a tenant filter; the row carries tenant_id.
// Used by /v1/ingest, which learns the tenant from the account.
func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.OwnerType,
		&i.Label,
		&i.PlatformIdentifier,
		&i.CredentialsEncrypted,
		&i.Capabilities,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountForTenant = `-- name: GetAccountForTenant :one
SELECT id, tenant_id, type, owner_type, label, platform_identifier, credentials_encrypted, capabilities, status, created_at FROM accounts
WHERE id = $1 AND tenant_id = $2
`

type GetAccountForTenantParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetAccountForTenant(ctx context.Context, arg GetAccountForTenantParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForTenant, arg.ID, arg.TenantID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.OwnerType,
		&i.Label,
		&i.PlatformIdentifier,
		&i.CredentialsEncrypted,
		&i.Capabilities,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountsForTenant = `-- name: ListAccountsForTenant :many
SELECT id, tenant_id, type, owner_type, label, platform_identifier, credentials_encrypted, capabilities, status, created_at FROM accounts
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAccountsForTenant(ctx context.Context, tenantID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.OwnerType,
			&i.Label,
			&i.PlatformIdentifier,
			&i.CredentialsEncrypted,
			&i.Capabilities,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsWithRoutingForTenant = `-- name: ListAccountsWithRoutingForTenant :many
SELECT a.id, a.tenant_id, a.type, a.owner_type, a.label, a.platform_identifier,
       a.capabilities, a.status, a.created_at,
       -- Emitted as text, '' when unlinked: sqlc infers a bare lateral column as
       -- NOT NULL and would fail the scan on every unrouted account. The service
       -- converts '' back to a nil channel id.
       COALESCE(inbound.id::text, '')::text AS inbound_channel_id
FROM accounts a
LEFT JOIN LATERAL (
  SELECT ch.id
  FROM channels ch
  JOIN channel_accounts ca ON ca.channel_id = ch.id
  WHERE ca.account_id = a.id AND ca.direction IN ('inbound', 'both')
  ORDER BY ca.priority DESC
  LIMIT 1
) inbound ON TRUE
WHERE a.tenant_id = $1
ORDER BY a.created_at DESC
`

type ListAccountsWithRoutingForTenantRow struct {
	ID                 uuid.UUID `db:"id" json:"id"`
	TenantID           uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Type               string    `db:"type" json:"type"`
	OwnerType          string    `db:"owner_type" json:"owner_type"`
	Label              string    `db:"label" json:"label"`
	PlatformIdentifier string    `db:"platform_identifier" json:"platform_identifier"`
	Capabilities       []string  `db:"capabilities" json:"capabilities"`
	Status             string    `db:"status" json:"status"`
	CreatedAt          time.Time `db:"created_at" json:"created_at"`
	InboundChannelID   string    `db:"inbound_channel_id" json:"inbound_channel_id"`
}

// Accounts plus the channel each one's INBOUND traffic actually resolves to —
// computed with the same rule ingest uses (highest-priority inbound/both link).
// A NULL inbound_channel_id means messages to that account reach no consumer:
// they fall back to the service defaults, land on clarify, and dispatch nothing.
// Surfacing it here is what stops that state from being invisible.
func (q *Queries) ListAccountsWithRoutingForTenant(ctx context.Context, tenantID uuid.UUID) ([]ListAccountsWithRoutingForTenantRow, error) {
	rows, err := q.db.Query(ctx, listAccountsWithRoutingForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsWithRoutingForTenantRow{}
	for rows.Next() {
		var i ListAccountsWithRoutingForTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.OwnerType,
			&i.Label,
			&i.PlatformIdentifier,
			&i.Capabilities,
			&i.Status,
			&i.CreatedAt,
			&i.InboundChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupAccount = `-- name: LookupAccount :one
SELECT id, tenant_id FROM accounts
WHERE type = $1 AND platform_identifier = $2 AND status = 'active'
`

type LookupAccountParams struct {
	Type               string `db:"type" json:"type"`
	PlatformIdentifier string `db:"platform_identifier" json:"platform_identifier"`
}

type LookupAccountRow struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

// Resolve an account by platform type + identifier (used by the webhook's
// account lookup). Returns only the ids — never credentials.
//
// Only an active account resolves. Suspending an account is the documented way
// to stop traffic from an abusive or compromised sender, and until this filter
// existed the status column was decorative: a suspended account kept accepting
// messages exactly as before, so an operator who suspended one would reasonably
// believe they had stopped it. A suspended account now looks unregistered to
// the webhook, which acknowledges and drops.
func (q *Queries) LookupAccount(ctx context.Context, arg LookupAccountParams) (LookupAccountRow, error) {
	row := q.db.QueryRow(ctx, lookupAccount, arg.Type, arg.PlatformIdentifier)
	var i LookupAccountRow
	err := row.Scan(&i.ID, &i.TenantID)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET label = $3,
    status = $4,
    capabilities = $5,
    credentials_encrypted = $6
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, type, owner_type, label, platform_identifier, credentials_encrypted, capabilities, status, created_at
`

type UpdateAccountParams struct {
	ID                   uuid.UUID `db:"id" json:"id"`
	TenantID             uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Label                string    `db:"label" json:"label"`
	Status               string    `db:"status" json:"status"`
	Capabilities         []string  `db:"capabilities" json:"capabilities"`
	CredentialsEncrypted []byte    `db:"credentials_encrypted" json:"credentials_encrypted"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.TenantID,
		arg.Label,
		arg.Status,
		arg.Capabilities,
		arg.CredentialsEncrypted,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.OwnerType,
		&i.Label,
		&i.PlatformIdentifier,
		&i.CredentialsEncrypted,
		&i.Capabilities,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
