// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package goqueries

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (
  id, tenant_id, name, parser_config, workflow_url, reply_policy,
  confidence_thresholds, echo_back_enabled, recall_window_seconds, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, name, parser_config, workflow_url, reply_policy,
          confidence_thresholds, echo_back_enabled, recall_window_seconds,
          audit_retention_years, created_at
`

type CreateChannelParams struct {
	ID                   uuid.UUID       `db:"id" json:"id"`
	TenantID             uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	Name                 string          `db:"name" json:"name"`
	ParserConfig         json.RawMessage `db:"parser_config" json:"parser_config"`
	WorkflowUrl          pgtype.Text     `db:"workflow_url" json:"workflow_url"`
	ReplyPolicy          string          `db:"reply_policy" json:"reply_policy"`
	ConfidenceThresholds json.RawMessage `db:"confidence_thresholds" json:"confidence_thresholds"`
	EchoBackEnabled      bool            `db:"echo_back_enabled" json:"echo_back_enabled"`
	RecallWindowSeconds  int32           `db:"recall_window_seconds" json:"recall_window_seconds"`
	CreatedAt            time.Time       `db:"created_at" json:"created_at"`
}

// Create a routing channel. Until this existed the row could only be written by
// hand in SQL, which meant a new deployment silently forwarded nothing: with no
// channel there is no workflow_url, and ingest falls back to defaults.
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.ParserConfig,
		arg.WorkflowUrl,
		arg.ReplyPolicy,
		arg.ConfidenceThresholds,
		arg.EchoBackEnabled,
		arg.RecallWindowSeconds,
		arg.CreatedAt,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ParserConfig,
		&i.WorkflowUrl,
		&i.ReplyPolicy,
		&i.ConfidenceThresholds,
		&i.EchoBackEnabled,
		&i.RecallWindowSeconds,
		&i.AuditRetentionYears,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelForTenant = `-- name: GetChannelForTenant :one
SELECT id, tenant_id, name, parser_config, workflow_url, reply_policy,
       confidence_thresholds, echo_back_enabled, recall_window_seconds,
       audit_retention_years, created_at
FROM channels
WHERE id = $1 AND tenant_id = $2
`

type GetChannelForTenantParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetChannelForTenant(ctx context.Context, arg GetChannelForTenantParams) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelForTenant, arg.ID, arg.TenantID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ParserConfig,
		&i.WorkflowUrl,
		&i.ReplyPolicy,
		&i.ConfidenceThresholds,
		&i.EchoBackEnabled,
		&i.RecallWindowSeconds,
		&i.AuditRetentionYears,
		&i.CreatedAt,
	)
	return i, err
}

const getInboundChannelForAccount = `-- name: GetInboundChannelForAccount :one
SELECT c.id, c.parser_config, c.confidence_thresholds, c.recall_window_seconds,
       c.workflow_url, c.reply_policy
FROM channels c
JOIN channel_accounts ca ON ca.channel_id = c.id
WHERE ca.account_id = $1 AND ca.direction IN ('inbound', 'both')
ORDER BY ca.priority DESC
LIMIT 1
`

type GetInboundChannelForAccountRow struct {
	ID                   uuid.UUID       `db:"id" json:"id"`
	ParserConfig         json.RawMessage `db:"parser_config" json:"parser_config"`
	ConfidenceThresholds json.RawMessage `db:"confidence_thresholds" json:"confidence_thresholds"`
	RecallWindowSeconds  int32           `db:"recall_window_seconds" json:"recall_window_seconds"`
	WorkflowUrl          pgtype.Text     `db:"workflow_url" json:"workflow_url"`
	ReplyPolicy          string          `db:"reply_policy" json:"reply_policy"`
}

// Resolve the logical channel an inbound message on this account belongs to,
// with its config. Highest-priority inbound/both link wins. Returns no row when
// the account isn't linked to a channel (ingest then falls back to defaults).
func (q *Queries) GetInboundChannelForAccount(ctx context.Context, accountID uuid.UUID) (GetInboundChannelForAccountRow, error) {
	row := q.db.QueryRow(ctx, getInboundChannelForAccount, accountID)
	var i GetInboundChannelForAccountRow
	err := row.Scan(
		&i.ID,
		&i.ParserConfig,
		&i.ConfidenceThresholds,
		&i.RecallWindowSeconds,
		&i.WorkflowUrl,
		&i.ReplyPolicy,
	)
	return i, err
}

const getOutboundAccountForChannel = `-- name: GetOutboundAccountForChannel :one
SELECT ca.account_id, ch.tenant_id
FROM channel_accounts ca
JOIN channels ch ON ch.id = ca.channel_id
WHERE ca.channel_id = $1 AND ca.direction IN ('outbound', 'both')
ORDER BY ca.priority DESC
LIMIT 1
`

type GetOutboundAccountForChannelRow struct {
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

// Resolve the account a channel sends from. Highest-priority outbound/both link
// wins (mirrors GetInboundChannelForAccount on the receive side). Used by
// /v1/outbound's recipient variant, which has no prior message to inherit an
// account from.
func (q *Queries) GetOutboundAccountForChannel(ctx context.Context, channelID uuid.UUID) (GetOutboundAccountForChannelRow, error) {
	row := q.db.QueryRow(ctx, getOutboundAccountForChannel, channelID)
	var i GetOutboundAccountForChannelRow
	err := row.Scan(&i.AccountID, &i.TenantID)
	return i, err
}

const linkAccountToChannel = `-- name: LinkAccountToChannel :one
INSERT INTO channel_accounts (channel_id, account_id, direction, priority, routing_filter)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (channel_id, account_id) DO UPDATE
SET direction = EXCLUDED.direction,
    priority = EXCLUDED.priority,
    routing_filter = EXCLUDED.routing_filter
RETURNING channel_id, account_id, direction, priority, routing_filter
`

type LinkAccountToChannelParams struct {
	ChannelID     uuid.UUID `db:"channel_id" json:"channel_id"`
	AccountID     uuid.UUID `db:"account_id" json:"account_id"`
	Direction     string    `db:"direction" json:"direction"`
	Priority      int32     `db:"priority" json:"priority"`
	RoutingFilter []byte    `db:"routing_filter" json:"routing_filter"`
}

// Idempotent link: re-linking an already-linked account updates the routing
// fields rather than erroring, so a console can PUT the desired state.
func (q *Queries) LinkAccountToChannel(ctx context.Context, arg LinkAccountToChannelParams) (ChannelAccount, error) {
	row := q.db.QueryRow(ctx, linkAccountToChannel,
		arg.ChannelID,
		arg.AccountID,
		arg.Direction,
		arg.Priority,
		arg.RoutingFilter,
	)
	var i ChannelAccount
	err := row.Scan(
		&i.ChannelID,
		&i.AccountID,
		&i.Direction,
		&i.Priority,
		&i.RoutingFilter,
	)
	return i, err
}

const listAccountLinksForChannel = `-- name: ListAccountLinksForChannel :many
SELECT ca.channel_id, ca.account_id, ca.direction, ca.priority, ca.routing_filter,
       a.type, a.platform_identifier, a.label, a.status
FROM channel_accounts ca
JOIN accounts a ON a.id = ca.account_id
WHERE ca.channel_id = $1
ORDER BY ca.priority DESC
`

type ListAccountLinksForChannelRow struct {
	ChannelID          uuid.UUID `db:"channel_id" json:"channel_id"`
	AccountID          uuid.UUID `db:"account_id" json:"account_id"`
	Direction          string    `db:"direction" json:"direction"`
	Priority           int32     `db:"priority" json:"priority"`
	RoutingFilter      []byte    `db:"routing_filter" json:"routing_filter"`
	Type               string    `db:"type" json:"type"`
	PlatformIdentifier string    `db:"platform_identifier" json:"platform_identifier"`
	Label              string    `db:"label" json:"label"`
	Status             string    `db:"status" json:"status"`
}

// The links on a channel, with enough account detail for a console to render
// them without a second round trip.
func (q *Queries) ListAccountLinksForChannel(ctx context.Context, channelID uuid.UUID) ([]ListAccountLinksForChannelRow, error) {
	rows, err := q.db.Query(ctx, listAccountLinksForChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountLinksForChannelRow{}
	for rows.Next() {
		var i ListAccountLinksForChannelRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.AccountID,
			&i.Direction,
			&i.Priority,
			&i.RoutingFilter,
			&i.Type,
			&i.PlatformIdentifier,
			&i.Label,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsForTenant = `-- name: ListChannelsForTenant :many
SELECT id, tenant_id, name, parser_config, workflow_url, reply_policy,
       confidence_thresholds, echo_back_enabled, recall_window_seconds,
       audit_retention_years, created_at
FROM channels
WHERE tenant_id = $1
ORDER BY created_at
`

func (q *Queries) ListChannelsForTenant(ctx context.Context, tenantID uuid.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ParserConfig,
			&i.WorkflowUrl,
			&i.ReplyPolicy,
			&i.ConfidenceThresholds,
			&i.EchoBackEnabled,
			&i.RecallWindowSeconds,
			&i.AuditRetentionYears,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkAccountFromChannel = `-- name: UnlinkAccountFromChannel :execrows
DELETE FROM channel_accounts WHERE channel_id = $1 AND account_id = $2
`

type UnlinkAccountFromChannelParams struct {
	ChannelID uuid.UUID `db:"channel_id" json:"channel_id"`
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
}

func (q *Queries) UnlinkAccountFromChannel(ctx context.Context, arg UnlinkAccountFromChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkAccountFromChannel, arg.ChannelID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name                  = COALESCE($1, name),
    parser_config         = COALESCE($2, parser_config),
    workflow_url          = COALESCE($3, workflow_url),
    reply_policy          = COALESCE($4, reply_policy),
    confidence_thresholds = COALESCE($5, confidence_thresholds),
    echo_back_enabled     = COALESCE($6, echo_back_enabled),
    recall_window_seconds = COALESCE($7, recall_window_seconds)
WHERE id = $8 AND tenant_id = $9
RETURNING id, tenant_id, name, parser_config, workflow_url, reply_policy,
          confidence_thresholds, echo_back_enabled, recall_window_seconds,
          audit_retention_years, created_at
`

type UpdateChannelParams struct {
	Name                 pgtype.Text `db:"name" json:"name"`
	ParserConfig         []byte      `db:"parser_config" json:"parser_config"`
	WorkflowUrl          pgtype.Text `db:"workflow_url" json:"workflow_url"`
	ReplyPolicy          pgtype.Text `db:"reply_policy" json:"reply_policy"`
	ConfidenceThresholds []byte      `db:"confidence_thresholds" json:"confidence_thresholds"`
	EchoBackEnabled      pgtype.Bool `db:"echo_back_enabled" json:"echo_back_enabled"`
	RecallWindowSeconds  pgtype.Int4 `db:"recall_window_seconds" json:"recall_window_seconds"`
	ID                   uuid.UUID   `db:"id" json:"id"`
	TenantID             uuid.UUID   `db:"tenant_id" json:"tenant_id"`
}

// Partial update: a NULL argument leaves the column untouched, so a caller can
// set workflow_url without restating the parser config.
func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.Name,
		arg.ParserConfig,
		arg.WorkflowUrl,
		arg.ReplyPolicy,
		arg.ConfidenceThresholds,
		arg.EchoBackEnabled,
		arg.RecallWindowSeconds,
		arg.ID,
		arg.TenantID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ParserConfig,
		&i.WorkflowUrl,
		&i.ReplyPolicy,
		&i.ConfidenceThresholds,
		&i.EchoBackEnabled,
		&i.RecallWindowSeconds,
		&i.AuditRetentionYears,
		&i.CreatedAt,
	)
	return i, err
}
