// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package goqueries

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
  id, tenant_id, short_id, display_name, aoi_id, role, status, metadata, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $9
)
RETURNING id, tenant_id, short_id, display_name, aoi_id, role, default_channel_id, status, metadata, created_at, updated_at
`

type CreateContactParams struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	TenantID    uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	ShortID     string          `db:"short_id" json:"short_id"`
	DisplayName string          `db:"display_name" json:"display_name"`
	AoiID       pgtype.Text     `db:"aoi_id" json:"aoi_id"`
	Role        pgtype.Text     `db:"role" json:"role"`
	Status      string          `db:"status" json:"status"`
	Metadata    json.RawMessage `db:"metadata" json:"metadata"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.ID,
		arg.TenantID,
		arg.ShortID,
		arg.DisplayName,
		arg.AoiID,
		arg.Role,
		arg.Status,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShortID,
		&i.DisplayName,
		&i.AoiID,
		&i.Role,
		&i.DefaultChannelID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :execrows
DELETE FROM contacts WHERE id = $1 AND tenant_id = $2
`

type DeleteContactParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContact, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getContactByShortID = `-- name: GetContactByShortID :one
SELECT id, tenant_id, short_id, display_name, aoi_id, role, default_channel_id, status, metadata, created_at, updated_at FROM contacts WHERE tenant_id = $1 AND short_id = $2
`

type GetContactByShortIDParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ShortID  string    `db:"short_id" json:"short_id"`
}

func (q *Queries) GetContactByShortID(ctx context.Context, arg GetContactByShortIDParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByShortID, arg.TenantID, arg.ShortID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShortID,
		&i.DisplayName,
		&i.AoiID,
		&i.Role,
		&i.DefaultChannelID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactForTenant = `-- name: GetContactForTenant :one
SELECT id, tenant_id, short_id, display_name, aoi_id, role, default_channel_id, status, metadata, created_at, updated_at FROM contacts WHERE id = $1 AND tenant_id = $2
`

type GetContactForTenantParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetContactForTenant(ctx context.Context, arg GetContactForTenantParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactForTenant, arg.ID, arg.TenantID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShortID,
		&i.DisplayName,
		&i.AoiID,
		&i.Role,
		&i.DefaultChannelID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboundEndpointForContact = `-- name: GetOutboundEndpointForContact :one
SELECT ce.endpoint, ce.account_id, ce.channel_id, c.tenant_id
FROM contact_endpoints ce
JOIN contacts c ON c.id = ce.contact_id
WHERE ce.contact_id = $1
  AND 'outbound' = ANY(ce.capabilities)
  AND ($2::uuid IS NULL OR ce.channel_id = $2::uuid)
ORDER BY ce.priority DESC
LIMIT 1
`

type GetOutboundEndpointForContactParams struct {
	ContactID uuid.UUID  `db:"contact_id" json:"contact_id"`
	ChannelID *uuid.UUID `db:"channel_id" json:"channel_id"`
}

type GetOutboundEndpointForContactRow struct {
	Endpoint  string    `db:"endpoint" json:"endpoint"`
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
	ChannelID uuid.UUID `db:"channel_id" json:"channel_id"`
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

// Resolve where to send a message addressed to a contact by id: the
// highest-priority endpoint that can send, plus the account to send it from.
// Optionally constrained to one channel (pass NULL for "any channel"). Used by
// /v1/outbound's recipient variant — unlike the reply path there is no prior
// message to inherit the endpoint/account from.
func (q *Queries) GetOutboundEndpointForContact(ctx context.Context, arg GetOutboundEndpointForContactParams) (GetOutboundEndpointForContactRow, error) {
	row := q.db.QueryRow(ctx, getOutboundEndpointForContact, arg.ContactID, arg.ChannelID)
	var i GetOutboundEndpointForContactRow
	err := row.Scan(
		&i.Endpoint,
		&i.AccountID,
		&i.ChannelID,
		&i.TenantID,
	)
	return i, err
}

const listContactShortIDs = `-- name: ListContactShortIDs :many
SELECT id, short_id, display_name FROM contacts WHERE tenant_id = $1
`

type ListContactShortIDsRow struct {
	ID          uuid.UUID `db:"id" json:"id"`
	ShortID     string    `db:"short_id" json:"short_id"`
	DisplayName string    `db:"display_name" json:"display_name"`
}

// Lightweight projection for the resolver candidate set + short_id_check.
func (q *Queries) ListContactShortIDs(ctx context.Context, tenantID uuid.UUID) ([]ListContactShortIDsRow, error) {
	rows, err := q.db.Query(ctx, listContactShortIDs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactShortIDsRow{}
	for rows.Next() {
		var i ListContactShortIDsRow
		if err := rows.Scan(&i.ID, &i.ShortID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsForTenant = `-- name: ListContactsForTenant :many
SELECT id, tenant_id, short_id, display_name, aoi_id, role, default_channel_id, status, metadata, created_at, updated_at FROM contacts WHERE tenant_id = $1 ORDER BY short_id
`

func (q *Queries) ListContactsForTenant(ctx context.Context, tenantID uuid.UUID) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContactsForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ShortID,
			&i.DisplayName,
			&i.AoiID,
			&i.Role,
			&i.DefaultChannelID,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET display_name = $3,
    aoi_id = $4,
    role = $5,
    status = $6,
    metadata = $7,
    updated_at = $8
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, short_id, display_name, aoi_id, role, default_channel_id, status, metadata, created_at, updated_at
`

type UpdateContactParams struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	TenantID    uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	DisplayName string          `db:"display_name" json:"display_name"`
	AoiID       pgtype.Text     `db:"aoi_id" json:"aoi_id"`
	Role        pgtype.Text     `db:"role" json:"role"`
	Status      string          `db:"status" json:"status"`
	Metadata    json.RawMessage `db:"metadata" json:"metadata"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.ID,
		arg.TenantID,
		arg.DisplayName,
		arg.AoiID,
		arg.Role,
		arg.Status,
		arg.Metadata,
		arg.UpdatedAt,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShortID,
		&i.DisplayName,
		&i.AoiID,
		&i.Role,
		&i.DefaultChannelID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
