// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diagnostics.sql

package goqueries

import (
	"context"

	"github.com/google/uuid"
)

const countAccountsForTenant = `-- name: CountAccountsForTenant :one

SELECT count(*) FROM accounts WHERE tenant_id = $1
`

// Queries behind GET /v1/diagnostics — the "why is nothing happening?" check.
//
// The failure these exist to surface is silent by construction: an account with
// no inbound channel link still accepts and stores messages, and forwards them
// nowhere. Nothing errors, the webhook returns 200, and the only evidence is one
// warning line in the channels container log. These turn that into a sentence.
func (q *Queries) CountAccountsForTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountsForTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChannelsForTenant = `-- name: CountChannelsForTenant :one
SELECT count(*) FROM channels WHERE tenant_id = $1
`

func (q *Queries) CountChannelsForTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelsForTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContactsForTenant = `-- name: CountContactsForTenant :one
SELECT count(*) FROM contacts WHERE tenant_id = $1
`

func (q *Queries) CountContactsForTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countContactsForTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesForTenant = `-- name: CountMessagesForTenant :one
SELECT count(*) FROM messages WHERE tenant_id = $1
`

func (q *Queries) CountMessagesForTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesForTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listChannelsWithoutWorkflow = `-- name: ListChannelsWithoutWorkflow :many
SELECT id, name FROM channels
WHERE tenant_id = $1 AND (workflow_url IS NULL OR workflow_url = '')
ORDER BY created_at
`

type ListChannelsWithoutWorkflowRow struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
}

// Channels that resolve inbound traffic but have nowhere to forward it to. Less
// severe than an unroutable account (parsing and storage still apply) but the
// consumer product never hears about the message.
func (q *Queries) ListChannelsWithoutWorkflow(ctx context.Context, tenantID uuid.UUID) ([]ListChannelsWithoutWorkflowRow, error) {
	rows, err := q.db.Query(ctx, listChannelsWithoutWorkflow, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelsWithoutWorkflowRow{}
	for rows.Next() {
		var i ListChannelsWithoutWorkflowRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnroutableAccounts = `-- name: ListUnroutableAccounts :many
SELECT a.id, a.type, a.platform_identifier, a.label
FROM accounts a
WHERE a.tenant_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM channel_accounts ca
    WHERE ca.account_id = a.id AND ca.direction IN ('inbound', 'both')
  )
ORDER BY a.created_at
`

type ListUnroutableAccountsRow struct {
	ID                 uuid.UUID `db:"id" json:"id"`
	Type               string    `db:"type" json:"type"`
	PlatformIdentifier string    `db:"platform_identifier" json:"platform_identifier"`
	Label              string    `db:"label" json:"label"`
}

// Accounts with no inbound-capable channel link. Every message arriving on one
// of these is stored and forwarded nowhere.
func (q *Queries) ListUnroutableAccounts(ctx context.Context, tenantID uuid.UUID) ([]ListUnroutableAccountsRow, error) {
	rows, err := q.db.Query(ctx, listUnroutableAccounts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnroutableAccountsRow{}
	for rows.Next() {
		var i ListUnroutableAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.PlatformIdentifier,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
