// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: export.sql

package goqueries

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const exportContactsPage = `-- name: ExportContactsPage :many
SELECT id, tenant_id, short_id, display_name, aoi_id, role,
       default_channel_id, status, metadata, created_at, updated_at
FROM contacts
WHERE tenant_id = $1
  AND (created_at, id) > ($3::timestamptz, $4::uuid)
ORDER BY created_at, id
LIMIT $2
`

type ExportContactsPageParams struct {
	TenantID       uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Limit          int32     `db:"limit" json:"limit"`
	AfterCreatedAt time.Time `db:"after_created_at" json:"after_created_at"`
	AfterID        uuid.UUID `db:"after_id" json:"after_id"`
}

// The address book, with each contact's endpoints inlined by the caller. Same
// keyset approach, ordered by the pair that is unique per tenant.
func (q *Queries) ExportContactsPage(ctx context.Context, arg ExportContactsPageParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, exportContactsPage,
		arg.TenantID,
		arg.Limit,
		arg.AfterCreatedAt,
		arg.AfterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ShortID,
			&i.DisplayName,
			&i.AoiID,
			&i.Role,
			&i.DefaultChannelID,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportEndpointsForContacts = `-- name: ExportEndpointsForContacts :many
SELECT ce.id, ce.contact_id, ce.channel_id, ce.account_id, ce.endpoint,
       ce.priority, ce.capabilities, ce.last_seen_at
FROM contact_endpoints ce
WHERE ce.contact_id = ANY($1::uuid[])
ORDER BY ce.contact_id, ce.priority DESC
`

type ExportEndpointsForContactsRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	ContactID    uuid.UUID  `db:"contact_id" json:"contact_id"`
	ChannelID    uuid.UUID  `db:"channel_id" json:"channel_id"`
	AccountID    uuid.UUID  `db:"account_id" json:"account_id"`
	Endpoint     string     `db:"endpoint" json:"endpoint"`
	Priority     int32      `db:"priority" json:"priority"`
	Capabilities []string   `db:"capabilities" json:"capabilities"`
	LastSeenAt   *time.Time `db:"last_seen_at" json:"last_seen_at"`
}

// Endpoints for a page of contacts, fetched in one round trip rather than per
// contact.
func (q *Queries) ExportEndpointsForContacts(ctx context.Context, contactIds []uuid.UUID) ([]ExportEndpointsForContactsRow, error) {
	rows, err := q.db.Query(ctx, exportEndpointsForContacts, contactIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportEndpointsForContactsRow{}
	for rows.Next() {
		var i ExportEndpointsForContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.ChannelID,
			&i.AccountID,
			&i.Endpoint,
			&i.Priority,
			&i.Capabilities,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportMessagesPage = `-- name: ExportMessagesPage :many

SELECT id, tenant_id, account_id, channel_id, direction,
       sender_contact_id, recipient_contact_id, sender_endpoint,
       body_text, body_attachments,
       -- COALESCE, because ST_AsGeoJSON returns NULL for a message with no
       -- location — which is most of them — and a NULL here fails the scan.
       COALESCE(ST_AsGeoJSON(body_location), '')::text AS body_location_geojson,
       parsed, policy_action, workflow_fired, in_reply_to_message_id,
       platform_message_id, raw_payload, received_at, processed_at
FROM messages
WHERE tenant_id = $1
  AND (received_at, id) > ($3::timestamptz, $4::uuid)
ORDER BY received_at, id
LIMIT $2
`

type ExportMessagesPageParams struct {
	TenantID        uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Limit           int32     `db:"limit" json:"limit"`
	AfterReceivedAt time.Time `db:"after_received_at" json:"after_received_at"`
	AfterID         uuid.UUID `db:"after_id" json:"after_id"`
}

type ExportMessagesPageRow struct {
	ID                  uuid.UUID       `db:"id" json:"id"`
	TenantID            uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	AccountID           *uuid.UUID      `db:"account_id" json:"account_id"`
	ChannelID           *uuid.UUID      `db:"channel_id" json:"channel_id"`
	Direction           string          `db:"direction" json:"direction"`
	SenderContactID     *uuid.UUID      `db:"sender_contact_id" json:"sender_contact_id"`
	RecipientContactID  *uuid.UUID      `db:"recipient_contact_id" json:"recipient_contact_id"`
	SenderEndpoint      pgtype.Text     `db:"sender_endpoint" json:"sender_endpoint"`
	BodyText            string          `db:"body_text" json:"body_text"`
	BodyAttachments     []byte          `db:"body_attachments" json:"body_attachments"`
	BodyLocationGeojson string          `db:"body_location_geojson" json:"body_location_geojson"`
	Parsed              []byte          `db:"parsed" json:"parsed"`
	PolicyAction        pgtype.Text     `db:"policy_action" json:"policy_action"`
	WorkflowFired       bool            `db:"workflow_fired" json:"workflow_fired"`
	InReplyToMessageID  *uuid.UUID      `db:"in_reply_to_message_id" json:"in_reply_to_message_id"`
	PlatformMessageID   string          `db:"platform_message_id" json:"platform_message_id"`
	RawPayload          json.RawMessage `db:"raw_payload" json:"raw_payload"`
	ReceivedAt          time.Time       `db:"received_at" json:"received_at"`
	ProcessedAt         *time.Time      `db:"processed_at" json:"processed_at"`
}

// Queries behind the data-export endpoints.
//
// Export exists because an adopter must be able to leave. A tool that holds a
// disaster response's message history in a database only its own code can read
// is not something a public agency should adopt, whatever its licence says.
// These stream the whole dataset in stable, non-proprietary JSON — no caps, no
// sampling, and keyset pagination so an export of any size runs in constant
// memory rather than loading the table.
// One page, oldest first, using a keyset cursor rather than OFFSET: OFFSET
// re-scans on every page and, worse, silently skips or repeats rows when
// traffic arrives mid-export. (received_at, id) is a total order because id is
// unique, so the cursor never straddles a tie.
func (q *Queries) ExportMessagesPage(ctx context.Context, arg ExportMessagesPageParams) ([]ExportMessagesPageRow, error) {
	rows, err := q.db.Query(ctx, exportMessagesPage,
		arg.TenantID,
		arg.Limit,
		arg.AfterReceivedAt,
		arg.AfterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportMessagesPageRow{}
	for rows.Next() {
		var i ExportMessagesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.ChannelID,
			&i.Direction,
			&i.SenderContactID,
			&i.RecipientContactID,
			&i.SenderEndpoint,
			&i.BodyText,
			&i.BodyAttachments,
			&i.BodyLocationGeojson,
			&i.Parsed,
			&i.PolicyAction,
			&i.WorkflowFired,
			&i.InReplyToMessageID,
			&i.PlatformMessageID,
			&i.RawPayload,
			&i.ReceivedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
