// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package goqueries

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInboundMessage = `-- name: CreateInboundMessage :one
INSERT INTO messages (
  id, tenant_id, account_id, channel_id, direction, sender_endpoint, body_text,
  body_attachments, parsed, policy_action, platform_message_id, raw_payload,
  received_at, processed_at, body_location
) VALUES (
  $1, $2, $3, $4, 'inbound', $5, $6, $7, $8, $9, $10, $11, $12, $13,
  NULLIF($14::text, '')::geography
)
ON CONFLICT (account_id, platform_message_id) DO NOTHING
RETURNING id
`

type CreateInboundMessageParams struct {
	ID                uuid.UUID       `db:"id" json:"id"`
	TenantID          uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	AccountID         *uuid.UUID      `db:"account_id" json:"account_id"`
	ChannelID         *uuid.UUID      `db:"channel_id" json:"channel_id"`
	SenderEndpoint    pgtype.Text     `db:"sender_endpoint" json:"sender_endpoint"`
	BodyText          string          `db:"body_text" json:"body_text"`
	BodyAttachments   []byte          `db:"body_attachments" json:"body_attachments"`
	Parsed            []byte          `db:"parsed" json:"parsed"`
	PolicyAction      pgtype.Text     `db:"policy_action" json:"policy_action"`
	PlatformMessageID string          `db:"platform_message_id" json:"platform_message_id"`
	RawPayload        json.RawMessage `db:"raw_payload" json:"raw_payload"`
	ReceivedAt        time.Time       `db:"received_at" json:"received_at"`
	ProcessedAt       *time.Time      `db:"processed_at" json:"processed_at"`
	BodyLocation      string          `db:"body_location" json:"body_location"`
}

// Persist an inbound message. Idempotent on (account_id, platform_message_id):
// a duplicate inserts nothing and returns no row (the handler then treats it as
// a replay). parsed carries the structured parse+resolution; policy_action is
// the gate's decision (confidence lives inside parsed).
// body_location takes EWKT ('SRID=4326;POINT(lng lat)'); ” means the sender
// provided no location and stores NULL. Passing text and casting keeps the
// generated param a plain string instead of an opaque geography type.
func (q *Queries) CreateInboundMessage(ctx context.Context, arg CreateInboundMessageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createInboundMessage,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.ChannelID,
		arg.SenderEndpoint,
		arg.BodyText,
		arg.BodyAttachments,
		arg.Parsed,
		arg.PolicyAction,
		arg.PlatformMessageID,
		arg.RawPayload,
		arg.ReceivedAt,
		arg.ProcessedAt,
		arg.BodyLocation,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createOutboundMessage = `-- name: CreateOutboundMessage :one
INSERT INTO messages (
  id, tenant_id, account_id, direction, recipient_contact_id, body_text,
  policy_action, in_reply_to_message_id, platform_message_id, raw_payload,
  received_at, processed_at
) VALUES (
  $1, $2, $3, 'outbound', $4, $5, $6, $7, $8, '{}', $9, $9
)
RETURNING id
`

type CreateOutboundMessageParams struct {
	ID                 uuid.UUID   `db:"id" json:"id"`
	TenantID           uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	AccountID          *uuid.UUID  `db:"account_id" json:"account_id"`
	RecipientContactID *uuid.UUID  `db:"recipient_contact_id" json:"recipient_contact_id"`
	BodyText           string      `db:"body_text" json:"body_text"`
	PolicyAction       pgtype.Text `db:"policy_action" json:"policy_action"`
	InReplyToMessageID *uuid.UUID  `db:"in_reply_to_message_id" json:"in_reply_to_message_id"`
	PlatformMessageID  string      `db:"platform_message_id" json:"platform_message_id"`
	ReceivedAt         time.Time   `db:"received_at" json:"received_at"`
}

// Persist an outbound message (e.g. an echo-back), linked to the inbound it
// replies to.
func (q *Queries) CreateOutboundMessage(ctx context.Context, arg CreateOutboundMessageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createOutboundMessage,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.RecipientContactID,
		arg.BodyText,
		arg.PolicyAction,
		arg.InReplyToMessageID,
		arg.PlatformMessageID,
		arg.ReceivedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findRecentEchoForSender = `-- name: FindRecentEchoForSender :one
SELECT id, body_text FROM messages
WHERE account_id = $1
  AND sender_endpoint = $2
  AND direction = 'inbound'
  AND policy_action = 'echo_back'
  AND received_at >= $3
ORDER BY received_at DESC
LIMIT 1
`

type FindRecentEchoForSenderParams struct {
	AccountID      *uuid.UUID  `db:"account_id" json:"account_id"`
	SenderEndpoint pgtype.Text `db:"sender_endpoint" json:"sender_endpoint"`
	ReceivedAt     time.Time   `db:"received_at" json:"received_at"`
}

type FindRecentEchoForSenderRow struct {
	ID       uuid.UUID `db:"id" json:"id"`
	BodyText string    `db:"body_text" json:"body_text"`
}

// The most recent inbound message from this sender on this account that was
// echoed back and is still inside the recall window ($3 = cutoff). Used to
// resolve an "OOPS" recall.
func (q *Queries) FindRecentEchoForSender(ctx context.Context, arg FindRecentEchoForSenderParams) (FindRecentEchoForSenderRow, error) {
	row := q.db.QueryRow(ctx, findRecentEchoForSender, arg.AccountID, arg.SenderEndpoint, arg.ReceivedAt)
	var i FindRecentEchoForSenderRow
	err := row.Scan(&i.ID, &i.BodyText)
	return i, err
}

const getMessageForOutbound = `-- name: GetMessageForOutbound :one
SELECT account_id, channel_id, tenant_id, sender_endpoint, sender_contact_id, raw_payload
FROM messages WHERE id = $1
`

type GetMessageForOutboundRow struct {
	AccountID       *uuid.UUID      `db:"account_id" json:"account_id"`
	ChannelID       *uuid.UUID      `db:"channel_id" json:"channel_id"`
	TenantID        uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	SenderEndpoint  pgtype.Text     `db:"sender_endpoint" json:"sender_endpoint"`
	SenderContactID *uuid.UUID      `db:"sender_contact_id" json:"sender_contact_id"`
	RawPayload      json.RawMessage `db:"raw_payload" json:"raw_payload"`
}

// Resolve the conversation context for a reply: the account it arrived on, the
// original sender to reply to, and raw_payload (email replies thread off the
// original RFC Message-ID carried there).
func (q *Queries) GetMessageForOutbound(ctx context.Context, id uuid.UUID) (GetMessageForOutboundRow, error) {
	row := q.db.QueryRow(ctx, getMessageForOutbound, id)
	var i GetMessageForOutboundRow
	err := row.Scan(
		&i.AccountID,
		&i.ChannelID,
		&i.TenantID,
		&i.SenderEndpoint,
		&i.SenderContactID,
		&i.RawPayload,
	)
	return i, err
}

const getMessageIDByPlatformID = `-- name: GetMessageIDByPlatformID :one
SELECT id FROM messages
WHERE account_id = $1 AND platform_message_id = $2
`

type GetMessageIDByPlatformIDParams struct {
	AccountID         *uuid.UUID `db:"account_id" json:"account_id"`
	PlatformMessageID string     `db:"platform_message_id" json:"platform_message_id"`
}

// Resolve an existing message id for the replay path.
func (q *Queries) GetMessageIDByPlatformID(ctx context.Context, arg GetMessageIDByPlatformIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getMessageIDByPlatformID, arg.AccountID, arg.PlatformMessageID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listUnfiredForwards = `-- name: ListUnfiredForwards :many
SELECT m.id, m.tenant_id, m.account_id, m.channel_id, m.sender_endpoint,
       m.body_text, m.body_attachments, m.parsed, m.received_at,
       -- GeoJSON rather than the raw geography: replay has to rebuild the same
       -- {lat,lng} a live forward sends. '' when absent, so the column stays
       -- non-null and the scan can't fail on a message with no location.
       COALESCE(ST_AsGeoJSON(m.body_location), '')::text AS body_location,
       a.type AS account_type,
       c.workflow_url
FROM messages m
JOIN channels c ON c.id = m.channel_id
JOIN accounts a ON a.id = m.account_id
WHERE m.tenant_id = $1
  AND m.direction = 'inbound'
  AND m.workflow_fired = FALSE
  AND m.policy_action IN ('routed', 'execute')
  AND c.workflow_url IS NOT NULL
  AND c.workflow_url <> ''
  AND m.received_at >= $2
  AND ($4::uuid IS NULL OR m.channel_id = $4::uuid)
ORDER BY m.received_at ASC
LIMIT $3
`

type ListUnfiredForwardsParams struct {
	TenantID   uuid.UUID  `db:"tenant_id" json:"tenant_id"`
	ReceivedAt time.Time  `db:"received_at" json:"received_at"`
	Limit      int32      `db:"limit" json:"limit"`
	ChannelID  *uuid.UUID `db:"channel_id" json:"channel_id"`
}

type ListUnfiredForwardsRow struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	TenantID        uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	AccountID       *uuid.UUID  `db:"account_id" json:"account_id"`
	ChannelID       *uuid.UUID  `db:"channel_id" json:"channel_id"`
	SenderEndpoint  pgtype.Text `db:"sender_endpoint" json:"sender_endpoint"`
	BodyText        string      `db:"body_text" json:"body_text"`
	BodyAttachments []byte      `db:"body_attachments" json:"body_attachments"`
	Parsed          []byte      `db:"parsed" json:"parsed"`
	ReceivedAt      time.Time   `db:"received_at" json:"received_at"`
	BodyLocation    string      `db:"body_location" json:"body_location"`
	AccountType     string      `db:"account_type" json:"account_type"`
	WorkflowUrl     pgtype.Text `db:"workflow_url" json:"workflow_url"`
}

// Inbound messages that should have reached a consumer and didn't:
// workflow_fired is still false, the channel has a workflow_url, and the policy
// gate decided to route them ('routed' on passthrough, 'execute' on structured).
// Everything needed to rebuild the forward payload is selected here, so a
// replay reconstructs from stored state rather than re-deriving it.
// Oldest first, so a consumer sees a replayed batch in the order it happened.
func (q *Queries) ListUnfiredForwards(ctx context.Context, arg ListUnfiredForwardsParams) ([]ListUnfiredForwardsRow, error) {
	rows, err := q.db.Query(ctx, listUnfiredForwards,
		arg.TenantID,
		arg.ReceivedAt,
		arg.Limit,
		arg.ChannelID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnfiredForwardsRow{}
	for rows.Next() {
		var i ListUnfiredForwardsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.ChannelID,
			&i.SenderEndpoint,
			&i.BodyText,
			&i.BodyAttachments,
			&i.Parsed,
			&i.ReceivedAt,
			&i.BodyLocation,
			&i.AccountType,
			&i.WorkflowUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageRecalled = `-- name: MarkMessageRecalled :exec
UPDATE messages SET policy_action = 'recalled' WHERE id = $1
`

func (q *Queries) MarkMessageRecalled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMessageRecalled, id)
	return err
}

const markWorkflowFired = `-- name: MarkWorkflowFired :exec
UPDATE messages SET workflow_fired = TRUE WHERE id = $1
`

func (q *Queries) MarkWorkflowFired(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWorkflowFired, id)
	return err
}
