// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package goqueries

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                   uuid.UUID `db:"id" json:"id"`
	TenantID             uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Type                 string    `db:"type" json:"type"`
	OwnerType            string    `db:"owner_type" json:"owner_type"`
	Label                string    `db:"label" json:"label"`
	PlatformIdentifier   string    `db:"platform_identifier" json:"platform_identifier"`
	CredentialsEncrypted []byte    `db:"credentials_encrypted" json:"credentials_encrypted"`
	Capabilities         []string  `db:"capabilities" json:"capabilities"`
	Status               string    `db:"status" json:"status"`
	CreatedAt            time.Time `db:"created_at" json:"created_at"`
}

type AuditLog struct {
	ID         int64      `db:"id" json:"id"`
	TenantID   uuid.UUID  `db:"tenant_id" json:"tenant_id"`
	ActorType  string     `db:"actor_type" json:"actor_type"`
	ActorID    *uuid.UUID `db:"actor_id" json:"actor_id"`
	Action     string     `db:"action" json:"action"`
	EntityType string     `db:"entity_type" json:"entity_type"`
	EntityID   *uuid.UUID `db:"entity_id" json:"entity_id"`
	Before     []byte     `db:"before" json:"before"`
	After      []byte     `db:"after" json:"after"`
	At         time.Time  `db:"at" json:"at"`
	Metadata   []byte     `db:"metadata" json:"metadata"`
}

type Channel struct {
	ID                   uuid.UUID       `db:"id" json:"id"`
	TenantID             uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	Name                 string          `db:"name" json:"name"`
	ParserConfig         json.RawMessage `db:"parser_config" json:"parser_config"`
	WorkflowUrl          pgtype.Text     `db:"workflow_url" json:"workflow_url"`
	ReplyPolicy          string          `db:"reply_policy" json:"reply_policy"`
	ConfidenceThresholds json.RawMessage `db:"confidence_thresholds" json:"confidence_thresholds"`
	EchoBackEnabled      bool            `db:"echo_back_enabled" json:"echo_back_enabled"`
	RecallWindowSeconds  int32           `db:"recall_window_seconds" json:"recall_window_seconds"`
	AuditRetentionYears  int32           `db:"audit_retention_years" json:"audit_retention_years"`
	CreatedAt            time.Time       `db:"created_at" json:"created_at"`
}

type ChannelAccount struct {
	ChannelID     uuid.UUID `db:"channel_id" json:"channel_id"`
	AccountID     uuid.UUID `db:"account_id" json:"account_id"`
	Direction     string    `db:"direction" json:"direction"`
	Priority      int32     `db:"priority" json:"priority"`
	RoutingFilter []byte    `db:"routing_filter" json:"routing_filter"`
}

type Contact struct {
	ID               uuid.UUID       `db:"id" json:"id"`
	TenantID         uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	ShortID          string          `db:"short_id" json:"short_id"`
	DisplayName      string          `db:"display_name" json:"display_name"`
	AoiID            pgtype.Text     `db:"aoi_id" json:"aoi_id"`
	Role             pgtype.Text     `db:"role" json:"role"`
	DefaultChannelID *uuid.UUID      `db:"default_channel_id" json:"default_channel_id"`
	Status           string          `db:"status" json:"status"`
	Metadata         json.RawMessage `db:"metadata" json:"metadata"`
	CreatedAt        time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time       `db:"updated_at" json:"updated_at"`
}

type ContactEndpoint struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	ContactID    uuid.UUID  `db:"contact_id" json:"contact_id"`
	ChannelID    uuid.UUID  `db:"channel_id" json:"channel_id"`
	AccountID    uuid.UUID  `db:"account_id" json:"account_id"`
	Endpoint     string     `db:"endpoint" json:"endpoint"`
	Priority     int32      `db:"priority" json:"priority"`
	Capabilities []string   `db:"capabilities" json:"capabilities"`
	LastSeenAt   *time.Time `db:"last_seen_at" json:"last_seen_at"`
	FailoverToID *uuid.UUID `db:"failover_to_id" json:"failover_to_id"`
}

type Group struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name     string    `db:"name" json:"name"`
	Type     string    `db:"type" json:"type"`
	Query    []byte    `db:"query" json:"query"`
}

type GroupMember struct {
	GroupID   uuid.UUID `db:"group_id" json:"group_id"`
	ContactID uuid.UUID `db:"contact_id" json:"contact_id"`
}

type Message struct {
	ID                 uuid.UUID       `db:"id" json:"id"`
	TenantID           uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	AccountID          *uuid.UUID      `db:"account_id" json:"account_id"`
	ChannelID          *uuid.UUID      `db:"channel_id" json:"channel_id"`
	Direction          string          `db:"direction" json:"direction"`
	SenderContactID    *uuid.UUID      `db:"sender_contact_id" json:"sender_contact_id"`
	RecipientContactID *uuid.UUID      `db:"recipient_contact_id" json:"recipient_contact_id"`
	SenderEndpoint     pgtype.Text     `db:"sender_endpoint" json:"sender_endpoint"`
	BodyText           string          `db:"body_text" json:"body_text"`
	BodyAttachments    []byte          `db:"body_attachments" json:"body_attachments"`
	BodyLocation       string          `db:"body_location" json:"body_location"`
	Parsed             []byte          `db:"parsed" json:"parsed"`
	PolicyAction       pgtype.Text     `db:"policy_action" json:"policy_action"`
	WorkflowFired      bool            `db:"workflow_fired" json:"workflow_fired"`
	InReplyToMessageID *uuid.UUID      `db:"in_reply_to_message_id" json:"in_reply_to_message_id"`
	PlatformMessageID  string          `db:"platform_message_id" json:"platform_message_id"`
	RawPayload         json.RawMessage `db:"raw_payload" json:"raw_payload"`
	ReceivedAt         time.Time       `db:"received_at" json:"received_at"`
	ProcessedAt        *time.Time      `db:"processed_at" json:"processed_at"`
}

type Tenant struct {
	ID        uuid.UUID       `db:"id" json:"id"`
	Name      string          `db:"name" json:"name"`
	Plan      string          `db:"plan" json:"plan"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
	Settings  json.RawMessage `db:"settings" json:"settings"`
}

type Workflow struct {
	ID                   uuid.UUID   `db:"id" json:"id"`
	ChannelID            uuid.UUID   `db:"channel_id" json:"channel_id"`
	Command              string      `db:"command" json:"command"`
	ActionType           string      `db:"action_type" json:"action_type"`
	ActionTarget         pgtype.Text `db:"action_target" json:"action_target"`
	ConfirmationRequired bool        `db:"confirmation_required" json:"confirmation_required"`
}
