// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package goqueries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Detach replies that point at messages about to be purged, so the delete does
	// not fail on messages_in_reply_to_message_id_fkey. The surviving message keeps
	// its own content; it just no longer points at a row that will not exist.
	ClearReplyLinksToPurgedMessages(ctx context.Context, arg ClearReplyLinksToPurgedMessagesParams) (int64, error)
	// Queries behind GET /v1/diagnostics — the "why is nothing happening?" check.
	//
	// The failure these exist to surface is silent by construction: an account with
	// no inbound channel link still accepts and stores messages, and forwards them
	// nowhere. Nothing errors, the webhook returns 200, and the only evidence is one
	// warning line in the channels container log. These turn that into a sentence.
	CountAccountsForTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountChannelsForTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountContactsForTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountMessagesForContact(ctx context.Context, arg CountMessagesForContactParams) (int64, error)
	CountMessagesForEndpoint(ctx context.Context, arg CountMessagesForEndpointParams) (int64, error)
	CountMessagesForTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	// Queries behind retention and erasure.
	//
	// Two different obligations, deliberately kept apart:
	//
	//   Retention  — delete everything older than a window the tenant sets. Blunt,
	//                scheduled, applies to all traffic.
	//   Erasure    — remove one person's personal data on request, without
	//                destroying the operational record that a message existed.
	//
	// Erasure redacts rather than deletes. A disaster response's message history is
	// an operational and often legal record: a missing-person report that vanishes
	// entirely can make an after-action review impossible and, in some
	// jurisdictions, breaks a retention duty that sits alongside the erasure right.
	// Redaction removes the identifying content — who sent it, what they said, the
	// verbatim provider envelope — while leaving the fact, timing, and routing of
	// the message intact. Where a tenant genuinely needs the row gone, retention
	// purge does that.
	CountMessagesOlderThan(ctx context.Context, arg CountMessagesOlderThanParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// Create a routing channel. Until this existed the row could only be written by
	// hand in SQL, which meant a new deployment silently forwarded nothing: with no
	// channel there is no workflow_url, and ingest falls back to defaults.
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	// Persist an inbound message. Idempotent on (account_id, platform_message_id):
	// a duplicate inserts nothing and returns no row (the handler then treats it as
	// a replay). parsed carries the structured parse+resolution; policy_action is
	// the gate's decision (confidence lives inside parsed).
	// body_location takes EWKT ('SRID=4326;POINT(lng lat)'); '' means the sender
	// provided no location and stores NULL. Passing text and casting keeps the
	// generated param a plain string instead of an opaque geography type.
	CreateInboundMessage(ctx context.Context, arg CreateInboundMessageParams) (uuid.UUID, error)
	// Persist an outbound message (e.g. an echo-back), linked to the inbound it
	// replies to.
	CreateOutboundMessage(ctx context.Context, arg CreateOutboundMessageParams) (uuid.UUID, error)
	// Bootstrap a tenant. Tenancy is provisioned out of band in FieldWatch's own
	// deployment, but an adopter starting from an empty database has no other way
	// in: accounts.tenant_id is a foreign key onto this table, so without a tenant
	// row every POST /v1/accounts fails the constraint and returns a bare
	// internal_error. Idempotent on id so a setup script can be re-run.
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error)
	DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error)
	DeleteContactRow(ctx context.Context, arg DeleteContactRowParams) (int64, error)
	DeleteEndpointsForContact(ctx context.Context, contactID uuid.UUID) (int64, error)
	// Drop the link between the message and the person, after redaction. The
	// message survives as an anonymous record of traffic.
	DetachMessagesFromContact(ctx context.Context, arg DetachMessagesFromContactParams) (int64, error)
	// The address book, with each contact's endpoints inlined by the caller. Same
	// keyset approach, ordered by the pair that is unique per tenant.
	ExportContactsPage(ctx context.Context, arg ExportContactsPageParams) ([]Contact, error)
	// Endpoints for a page of contacts, fetched in one round trip rather than per
	// contact.
	ExportEndpointsForContacts(ctx context.Context, contactIds []uuid.UUID) ([]ExportEndpointsForContactsRow, error)
	// Queries behind the data-export endpoints.
	//
	// Export exists because an adopter must be able to leave. A tool that holds a
	// disaster response's message history in a database only its own code can read
	// is not something a public agency should adopt, whatever its licence says.
	// These stream the whole dataset in stable, non-proprietary JSON — no caps, no
	// sampling, and keyset pagination so an export of any size runs in constant
	// memory rather than loading the table.
	// One page, oldest first, using a keyset cursor rather than OFFSET: OFFSET
	// re-scans on every page and, worse, silently skips or repeats rows when
	// traffic arrives mid-export. (received_at, id) is a total order because id is
	// unique, so the cursor never straddles a tie.
	ExportMessagesPage(ctx context.Context, arg ExportMessagesPageParams) ([]ExportMessagesPageRow, error)
	// The most recent inbound message from this sender on this account that was
	// echoed back and is still inside the recall window ($3 = cutoff). Used to
	// resolve an "OOPS" recall.
	FindRecentEchoForSender(ctx context.Context, arg FindRecentEchoForSenderParams) (FindRecentEchoForSenderRow, error)
	// Resolve an account by id without a tenant filter; the row carries tenant_id.
	// Used by /v1/ingest, which learns the tenant from the account.
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountForTenant(ctx context.Context, arg GetAccountForTenantParams) (Account, error)
	GetChannelForTenant(ctx context.Context, arg GetChannelForTenantParams) (Channel, error)
	GetContactByShortID(ctx context.Context, arg GetContactByShortIDParams) (Contact, error)
	GetContactForTenant(ctx context.Context, arg GetContactForTenantParams) (Contact, error)
	// Resolve the logical channel an inbound message on this account belongs to,
	// with its config. Highest-priority inbound/both link wins. Returns no row when
	// the account isn't linked to a channel (ingest then falls back to defaults).
	GetInboundChannelForAccount(ctx context.Context, accountID uuid.UUID) (GetInboundChannelForAccountRow, error)
	// Resolve the conversation context for a reply: the account it arrived on, the
	// original sender to reply to, and raw_payload (email replies thread off the
	// original RFC Message-ID carried there).
	GetMessageForOutbound(ctx context.Context, id uuid.UUID) (GetMessageForOutboundRow, error)
	// Resolve an existing message id for the replay path.
	GetMessageIDByPlatformID(ctx context.Context, arg GetMessageIDByPlatformIDParams) (uuid.UUID, error)
	// Resolve the account a channel sends from. Highest-priority outbound/both link
	// wins (mirrors GetInboundChannelForAccount on the receive side). Used by
	// /v1/outbound's recipient variant, which has no prior message to inherit an
	// account from.
	GetOutboundAccountForChannel(ctx context.Context, channelID uuid.UUID) (GetOutboundAccountForChannelRow, error)
	// Resolve where to send a message addressed to a contact by id: the
	// highest-priority endpoint that can send, plus the account to send it from.
	// Optionally constrained to one channel (pass NULL for "any channel"). Used by
	// /v1/outbound's recipient variant — unlike the reply path there is no prior
	// message to inherit the endpoint/account from.
	GetOutboundEndpointForContact(ctx context.Context, arg GetOutboundEndpointForContactParams) (GetOutboundEndpointForContactRow, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	// Idempotent link: re-linking an already-linked account updates the routing
	// fields rather than erroring, so a console can PUT the desired state.
	LinkAccountToChannel(ctx context.Context, arg LinkAccountToChannelParams) (ChannelAccount, error)
	// The links on a channel, with enough account detail for a console to render
	// them without a second round trip.
	ListAccountLinksForChannel(ctx context.Context, channelID uuid.UUID) ([]ListAccountLinksForChannelRow, error)
	ListAccountsForTenant(ctx context.Context, tenantID uuid.UUID) ([]Account, error)
	// Accounts plus the channel each one's INBOUND traffic actually resolves to —
	// computed with the same rule ingest uses (highest-priority inbound/both link).
	// A NULL inbound_channel_id means messages to that account reach no consumer:
	// they fall back to the service defaults, land on clarify, and dispatch nothing.
	// Surfacing it here is what stops that state from being invisible.
	ListAccountsWithRoutingForTenant(ctx context.Context, tenantID uuid.UUID) ([]ListAccountsWithRoutingForTenantRow, error)
	ListChannelsForTenant(ctx context.Context, tenantID uuid.UUID) ([]Channel, error)
	// Channels that resolve inbound traffic but have nowhere to forward it to. Less
	// severe than an unroutable account (parsing and storage still apply) but the
	// consumer product never hears about the message.
	ListChannelsWithoutWorkflow(ctx context.Context, tenantID uuid.UUID) ([]ListChannelsWithoutWorkflowRow, error)
	// Lightweight projection for the resolver candidate set + short_id_check.
	ListContactShortIDs(ctx context.Context, tenantID uuid.UUID) ([]ListContactShortIDsRow, error)
	ListContactsForTenant(ctx context.Context, tenantID uuid.UUID) ([]Contact, error)
	ListEndpointsForContact(ctx context.Context, contactID uuid.UUID) ([]string, error)
	// Recent traffic for the console. Deliberately excludes raw_payload (the
	// verbatim provider envelope, the largest and most sensitive column) and
	// credentials never appear here at all — this feeds a read-only view whose
	// whole job is letting an operator confirm that messages are arriving and being
	// understood.
	ListRecentMessagesForTenant(ctx context.Context, arg ListRecentMessagesForTenantParams) ([]ListRecentMessagesForTenantRow, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	// Inbound messages that should have reached a consumer and didn't:
	// workflow_fired is still false, the channel has a workflow_url, and the policy
	// gate decided to route them ('routed' on passthrough, 'execute' on structured).
	// Everything needed to rebuild the forward payload is selected here, so a
	// replay reconstructs from stored state rather than re-deriving it.
	// Oldest first, so a consumer sees a replayed batch in the order it happened.
	ListUnfiredForwards(ctx context.Context, arg ListUnfiredForwardsParams) ([]ListUnfiredForwardsRow, error)
	// Accounts with no inbound-capable channel link. Every message arriving on one
	// of these is stored and forwarded nowhere.
	ListUnroutableAccounts(ctx context.Context, tenantID uuid.UUID) ([]ListUnroutableAccountsRow, error)
	// Resolve an account by platform type + identifier (used by the webhook's
	// account lookup). Returns only the ids — never credentials.
	//
	// Only an active account resolves. Suspending an account is the documented way
	// to stop traffic from an abusive or compromised sender, and until this filter
	// existed the status column was decorative: a suspended account kept accepting
	// messages exactly as before, so an operator who suspended one would reasonably
	// believe they had stopped it. A suspended account now looks unregistered to
	// the webhook, which acknowledges and drops.
	LookupAccount(ctx context.Context, arg LookupAccountParams) (LookupAccountRow, error)
	MarkMessageRecalled(ctx context.Context, id uuid.UUID) error
	MarkWorkflowFired(ctx context.Context, id uuid.UUID) error
	// Trivial round-trip used to verify the pool can execute a query end to end.
	// Feature queries (accounts, messages, ...) are added by their own stories.
	Ping(ctx context.Context) (int32, error)
	// Hard delete. in_reply_to_message_id is self-referential, so clear inbound
	// references first (below) or the FK blocks the delete.
	PurgeMessagesOlderThan(ctx context.Context, arg PurgeMessagesOlderThanParams) (int64, error)
	// Erasure. Strips the personal content and the raw envelope, and marks the row
	// so a later reader can tell redaction from an empty message.
	RedactMessagesForContact(ctx context.Context, arg RedactMessagesForContactParams) (int64, error)
	// Erasure keyed on the endpoint — the phone number, address or handle a person
	// actually appears under in the messages table.
	//
	// This is the query that does the real work. sender_contact_id exists in the
	// schema but ingest does not populate it: resolving an inbound sender to an
	// address-book entry is not something the pipeline does yet, so the identifying
	// value on a stored message is sender_endpoint. A data-subject request also
	// arrives as an endpoint ("delete my data, my number is …"), not as an internal
	// contact id, so this matches how the request is actually made.
	RedactMessagesForEndpoint(ctx context.Context, arg RedactMessagesForEndpointParams) (int64, error)
	UnlinkAccountFromChannel(ctx context.Context, arg UnlinkAccountFromChannelParams) (int64, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	// Partial update: a NULL argument leaves the column untouched, so a caller can
	// set workflow_url without restating the parser config.
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
}

var _ Querier = (*Queries)(nil)
