// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: retention.sql

package goqueries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearReplyLinksToPurgedMessages = `-- name: ClearReplyLinksToPurgedMessages :execrows
UPDATE messages m SET in_reply_to_message_id = NULL
WHERE m.tenant_id = $1
  AND m.in_reply_to_message_id IN (
    SELECT old.id FROM messages old
    WHERE old.tenant_id = $1 AND old.received_at < $2
  )
`

type ClearReplyLinksToPurgedMessagesParams struct {
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ReceivedAt time.Time `db:"received_at" json:"received_at"`
}

// Detach replies that point at messages about to be purged, so the delete does
// not fail on messages_in_reply_to_message_id_fkey. The surviving message keeps
// its own content; it just no longer points at a row that will not exist.
func (q *Queries) ClearReplyLinksToPurgedMessages(ctx context.Context, arg ClearReplyLinksToPurgedMessagesParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearReplyLinksToPurgedMessages, arg.TenantID, arg.ReceivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countMessagesForContact = `-- name: CountMessagesForContact :one
SELECT count(*) FROM messages
WHERE tenant_id = $1 AND (sender_contact_id = $2 OR recipient_contact_id = $2)
`

type CountMessagesForContactParams struct {
	TenantID        uuid.UUID  `db:"tenant_id" json:"tenant_id"`
	SenderContactID *uuid.UUID `db:"sender_contact_id" json:"sender_contact_id"`
}

func (q *Queries) CountMessagesForContact(ctx context.Context, arg CountMessagesForContactParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesForContact, arg.TenantID, arg.SenderContactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesForEndpoint = `-- name: CountMessagesForEndpoint :one
SELECT count(*) FROM messages WHERE tenant_id = $1 AND sender_endpoint = $2
`

type CountMessagesForEndpointParams struct {
	TenantID       uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	SenderEndpoint pgtype.Text `db:"sender_endpoint" json:"sender_endpoint"`
}

func (q *Queries) CountMessagesForEndpoint(ctx context.Context, arg CountMessagesForEndpointParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesForEndpoint, arg.TenantID, arg.SenderEndpoint)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesOlderThan = `-- name: CountMessagesOlderThan :one

SELECT count(*) FROM messages WHERE tenant_id = $1 AND received_at < $2
`

type CountMessagesOlderThanParams struct {
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ReceivedAt time.Time `db:"received_at" json:"received_at"`
}

// Queries behind retention and erasure.
//
// Two different obligations, deliberately kept apart:
//
//	Retention  — delete everything older than a window the tenant sets. Blunt,
//	             scheduled, applies to all traffic.
//	Erasure    — remove one person's personal data on request, without
//	             destroying the operational record that a message existed.
//
// Erasure redacts rather than deletes. A disaster response's message history is
// an operational and often legal record: a missing-person report that vanishes
// entirely can make an after-action review impossible and, in some
// jurisdictions, breaks a retention duty that sits alongside the erasure right.
// Redaction removes the identifying content — who sent it, what they said, the
// verbatim provider envelope — while leaving the fact, timing, and routing of
// the message intact. Where a tenant genuinely needs the row gone, retention
// purge does that.
func (q *Queries) CountMessagesOlderThan(ctx context.Context, arg CountMessagesOlderThanParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesOlderThan, arg.TenantID, arg.ReceivedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteContactRow = `-- name: DeleteContactRow :execrows
DELETE FROM contacts WHERE id = $1 AND tenant_id = $2
`

type DeleteContactRowParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteContactRow(ctx context.Context, arg DeleteContactRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContactRow, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEndpointsForContact = `-- name: DeleteEndpointsForContact :execrows
DELETE FROM contact_endpoints WHERE contact_id = $1
`

func (q *Queries) DeleteEndpointsForContact(ctx context.Context, contactID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEndpointsForContact, contactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const detachMessagesFromContact = `-- name: DetachMessagesFromContact :execrows
UPDATE messages SET sender_contact_id = NULL, recipient_contact_id = NULL
WHERE tenant_id = $1 AND (sender_contact_id = $2 OR recipient_contact_id = $2)
`

type DetachMessagesFromContactParams struct {
	TenantID        uuid.UUID  `db:"tenant_id" json:"tenant_id"`
	SenderContactID *uuid.UUID `db:"sender_contact_id" json:"sender_contact_id"`
}

// Drop the link between the message and the person, after redaction. The
// message survives as an anonymous record of traffic.
func (q *Queries) DetachMessagesFromContact(ctx context.Context, arg DetachMessagesFromContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, detachMessagesFromContact, arg.TenantID, arg.SenderContactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEndpointsForContact = `-- name: ListEndpointsForContact :many
SELECT endpoint FROM contact_endpoints WHERE contact_id = $1
`

func (q *Queries) ListEndpointsForContact(ctx context.Context, contactID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listEndpointsForContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var endpoint string
		if err := rows.Scan(&endpoint); err != nil {
			return nil, err
		}
		items = append(items, endpoint)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeMessagesOlderThan = `-- name: PurgeMessagesOlderThan :execrows
DELETE FROM messages WHERE tenant_id = $1 AND received_at < $2
`

type PurgeMessagesOlderThanParams struct {
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ReceivedAt time.Time `db:"received_at" json:"received_at"`
}

// Hard delete. in_reply_to_message_id is self-referential, so clear inbound
// references first (below) or the FK blocks the delete.
func (q *Queries) PurgeMessagesOlderThan(ctx context.Context, arg PurgeMessagesOlderThanParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeMessagesOlderThan, arg.TenantID, arg.ReceivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const redactMessagesForContact = `-- name: RedactMessagesForContact :execrows
UPDATE messages
SET sender_endpoint = NULL,
    body_text       = '',
    body_attachments = NULL,
    body_location   = NULL,
    raw_payload     = '{"redacted": true}'::jsonb,
    parsed          = COALESCE(parsed, '{}'::jsonb) || '{"redacted": true}'::jsonb
WHERE tenant_id = $1
  AND (sender_contact_id = $2 OR recipient_contact_id = $2)
`

type RedactMessagesForContactParams struct {
	TenantID        uuid.UUID  `db:"tenant_id" json:"tenant_id"`
	SenderContactID *uuid.UUID `db:"sender_contact_id" json:"sender_contact_id"`
}

// Erasure. Strips the personal content and the raw envelope, and marks the row
// so a later reader can tell redaction from an empty message.
func (q *Queries) RedactMessagesForContact(ctx context.Context, arg RedactMessagesForContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, redactMessagesForContact, arg.TenantID, arg.SenderContactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const redactMessagesForEndpoint = `-- name: RedactMessagesForEndpoint :execrows
UPDATE messages
SET sender_endpoint  = NULL,
    body_text        = '',
    body_attachments = NULL,
    body_location    = NULL,
    raw_payload      = '{"redacted": true}'::jsonb,
    parsed           = COALESCE(parsed, '{}'::jsonb) || '{"redacted": true}'::jsonb
WHERE tenant_id = $1 AND sender_endpoint = $2
`

type RedactMessagesForEndpointParams struct {
	TenantID       uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	SenderEndpoint pgtype.Text `db:"sender_endpoint" json:"sender_endpoint"`
}

// Erasure keyed on the endpoint — the phone number, address or handle a person
// actually appears under in the messages table.
//
// This is the query that does the real work. sender_contact_id exists in the
// schema but ingest does not populate it: resolving an inbound sender to an
// address-book entry is not something the pipeline does yet, so the identifying
// value on a stored message is sender_endpoint. A data-subject request also
// arrives as an endpoint ("delete my data, my number is …"), not as an internal
// contact id, so this matches how the request is actually made.
func (q *Queries) RedactMessagesForEndpoint(ctx context.Context, arg RedactMessagesForEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, redactMessagesForEndpoint, arg.TenantID, arg.SenderEndpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
