// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system.sql

package goqueries

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1 AS ok
`

// Trivial round-trip used to verify the pool can execute a query end to end.
// Feature queries (accounts, messages, ...) are added by their own stories.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
