// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package goqueries

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, name, plan, created_at, settings)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO NOTHING
RETURNING id, name, plan, created_at, settings
`

type CreateTenantParams struct {
	ID        uuid.UUID       `db:"id" json:"id"`
	Name      string          `db:"name" json:"name"`
	Plan      string          `db:"plan" json:"plan"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
	Settings  json.RawMessage `db:"settings" json:"settings"`
}

// Bootstrap a tenant. Tenancy is provisioned out of band in FieldWatch's own
// deployment, but an adopter starting from an empty database has no other way
// in: accounts.tenant_id is a foreign key onto this table, so without a tenant
// row every POST /v1/accounts fails the constraint and returns a bare
// internal_error. Idempotent on id so a setup script can be re-run.
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.Plan,
		arg.CreatedAt,
		arg.Settings,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.Settings,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, plan, created_at, settings FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.Settings,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, plan, created_at, settings FROM tenants ORDER BY created_at
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Plan,
			&i.CreatedAt,
			&i.Settings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
